# Generated by Django 4.2.3 on 2023-07-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
